# Generated by Django 6.0.4 on 2026-04-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='urgente',
            field=models.BooleanField(default=False, help_text='Alerte prioritaire à afficher en bannière'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('courrier_affecte', 'Courrier affecté'), ('courrier_renvoye', 'Courrier renvoyé'), ('courrier_urgent', 'Courrier urgent'), ('document_partage', 'Document partagé'), ('commentaire', 'Nouveau commentaire'), ('tache', 'Nouvelle tâche'), ('system', 'Notification système')], default='system', max_length=30),
        ),
    ]
