# Generated by Django 5.2.11 on 2026-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_log_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('rh', 'RH'), ('collaborator', 'Collaborateur'), ('client', 'Client')], default='collaborator', max_length=20),
        ),
    ]
