# Generated by Django 5.2.11 on 2026-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_service_user_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_electronique',
            field=models.ImageField(blank=True, help_text="Image de la signature électronique de l'utilisateur (PNG recommandé avec fond transparent)", null=True, upload_to='signatures/%Y/%m/'),
        ),
    ]
