# Generated by Django 5.2.11 on 2026-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_signature_electronique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_password',
            field=models.CharField(blank=True, help_text='Mot de passe hashé pour valider la signature électronique', max_length=255, null=True),
        ),
    ]
