# Generated by Django 5.2.11 on 2026-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('rh', 'RH'), ('dg', 'Directeur Général'), ('collaborator', 'Collaborateur'), ('client', 'Client')], default='collaborator', max_length=20),
        ),
    ]
