# Generated by Django 5.2.11 on 2026-02-25 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_alter_tag_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('entrant', 'Courrier entrant'), ('sortant', 'Courrier sortant')], max_length=10)),
                ('objet', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='en_attente', max_length=20)),
                ('expediteur', models.CharField(blank=True, help_text='Organisme externe qui envoie', max_length=255)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('destinataire', models.CharField(blank=True, help_text='Organisme externe destinataire', max_length=255)),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('mode_envoi', models.CharField(blank=True, choices=[('courrier', 'Courrier postal'), ('email', 'Email'), ('fax', 'Fax'), ('main', 'Remise en main propre'), ('huissier', 'Huissier')], max_length=20)),
                ('reponse_a', models.CharField(blank=True, help_text='Référence du courrier auquel on répond', max_length=50)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='courriers/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers', to='tags.tag')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers_crees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_service', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='courriers_c_created_bcc847_idx'), models.Index(fields=['reference'], name='courriers_c_referen_78c9a9_idx'), models.Index(fields=['type', 'statut'], name='courriers_c_type_3e9244_idx')],
            },
        ),
    ]
