# Generated by Django 5.2.11 on 2026-04-07 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_affectationcourrier_circuit_and_more'),
        ('users', '0008_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_circuit', models.CharField(choices=[('simultane', 'Simultané'), ('sequentiel', 'Séquentiel')], default='simultane', help_text='Simultané : tous traitent en même temps. Séquentiel : étape par étape.', max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('titre', models.CharField(blank=True, help_text='Titre ou description courte du circuit (optionnel)', max_length=255)),
                ('instructions_generales', models.TextField(blank=True, help_text="Instructions générales valables pour l'ensemble du circuit")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (flexible)')),
                ('courrier', models.ForeignKey(help_text='Courrier concerné par ce circuit', on_delete=django.db.models.deletion.CASCADE, related_name='circuits_v2', to='documents.courrier')),
                ('cree_par', models.ForeignKey(help_text='Utilisateur ayant créé ce circuit (RH, Admin…)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits_v2_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Circuit d'affectation",
                'verbose_name_plural': "Circuits d'affectation",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_requise', models.CharField(choices=[('informatif', 'À titre informatif'), ('a_signer', 'À signer'), ('accusation_reception', 'À accuser de réception'), ('a_repondre', 'À répondre'), ('a_valider', 'À valider'), ('a_annoter', 'À annoter')], default='informatif', help_text='Ce que le destinataire doit faire avec ce courrier', max_length=30)),
                ('note_instruction', models.TextField(blank=True, help_text="Instructions spécifiques de l'affecteur pour cette affectation")),
                ('niveau_urgence', models.CharField(choices=[('faible', 'Faible'), ('normal', 'Normal'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='normal', max_length=20)),
                ('date_echeance', models.DateTimeField(blank=True, help_text='Date et heure limite pour traiter cette affectation', null=True)),
                ('etape_numero', models.PositiveIntegerField(default=1, help_text="N° d'étape dans le circuit séquentiel (toutes à 1 en simultané)")),
                ('statut', models.CharField(choices=[('distribue', 'Distribué'), ('vu', 'Vu'), ('en_traitement', 'En traitement'), ('valide', 'Validé'), ('signe', 'Signé'), ('rejete', 'Rejeté'), ('renvoye', 'Renvoyé')], default='distribue', max_length=20)),
                ('commentaire_traitement', models.TextField(blank=True, help_text='Commentaire du destinataire lors du traitement')),
                ('motif_rejet', models.TextField(blank=True, help_text='Motif en cas de rejet')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Première ouverture par le destinataire', null=True)),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date de validation / rejet / signature', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires flexibles (pièces jointes, tags, etc.)')),
                ('affecte_par', models.ForeignKey(help_text='Utilisateur qui a créé cette affectation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_v2_creees', to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(help_text='Courrier concerné (copie de circuit.courrier pour accès direct)', on_delete=django.db.models.deletion.CASCADE, related_name='affectations_v2', to='documents.courrier')),
                ('destinataire', models.ForeignKey(help_text='Utilisateur à qui le courrier est affecté', on_delete=django.db.models.deletion.CASCADE, related_name='affectations_v2_recues', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, help_text='Service concerné (optionnel, déduit du destinataire si absent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_v2', to='users.service')),
                ('circuit', models.ForeignKey(help_text='Circuit auquel appartient cette affectation', on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='affectations.circuit')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['etape_numero', '-date_affectation'],
            },
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['-date_creation'], name='affectation_date_cr_920e76_idx'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['courrier', 'statut'], name='affectation_courrie_779527_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['destinataire', 'statut'], name='affectation_destina_db919e_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['circuit', 'etape_numero'], name='affectation_circuit_94b040_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['-date_affectation'], name='affectation_date_af_24248b_idx'),
        ),
    ]
