# Generated by Django 6.0.4 on 2026-04-13 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registre', models.CharField(editable=False, help_text="Numéro d'enregistrement généré automatiquement", max_length=50, unique=True)),
                ('type_courrier', models.CharField(choices=[('entrant', 'Courrier Entrant'), ('sortant', 'Courrier Sortant'), ('interne', 'Courrier Interne')], help_text='Type de courrier (entrant ou sortant)', max_length=20)),
                ('date_reception', models.DateField(blank=True, help_text='Date de réception du courrier entrant', null=True)),
                ('mode_reception', models.CharField(blank=True, choices=[('postal', 'Courrier postal'), ('email', 'Email'), ('fax', 'Fax'), ('main_propre', 'Remise en main propre'), ('coursier', 'Coursier'), ('autre', 'Autre')], default='', help_text='Mode de réception du courrier entrant', max_length=50)),
                ('date_envoi', models.DateField(blank=True, help_text="Date d'envoi du courrier sortant", null=True)),
                ('mode_envoi', models.CharField(blank=True, choices=[('postal', 'Courrier postal'), ('email', 'Email'), ('fax', 'Fax'), ('main_propre', 'Remise en main propre'), ('coursier', 'Coursier'), ('autre', 'Autre')], default='', help_text="Mode d'envoi du courrier sortant", max_length=50)),
                ('date_circulation', models.DateField(blank=True, help_text='Date de circulation du courrier interne', null=True)),
                ('expediteur', models.CharField(blank=True, default='', help_text="Nom ou organisation de l'expéditeur (courrier entrant)", max_length=255)),
                ('destinataire', models.CharField(blank=True, default='', help_text='Nom ou organisation du destinataire (courrier sortant)', max_length=255)),
                ('service_emetteur', models.CharField(blank=True, choices=[('rh', 'Ressources Humaines'), ('comptabilite', 'Comptabilité'), ('direction', 'Direction'), ('technique', 'Service Technique'), ('commercial', 'Commercial'), ('juridique', 'Juridique'), ('informatique', 'Informatique'), ('logistique', 'Logistique'), ('autre', 'Autre')], default='', help_text='Service émetteur (courrier interne)', max_length=50)),
                ('service_destinataire', models.CharField(blank=True, choices=[('rh', 'Ressources Humaines'), ('comptabilite', 'Comptabilité'), ('direction', 'Direction'), ('technique', 'Service Technique'), ('commercial', 'Commercial'), ('juridique', 'Juridique'), ('informatique', 'Informatique'), ('logistique', 'Logistique'), ('autre', 'Autre')], default='', help_text='Service destinataire (courrier interne)', max_length=50)),
                ('objet', models.CharField(help_text='Objet ou sujet du courrier', max_length=500)),
                ('reference', models.CharField(blank=True, help_text='Référence du courrier (ex: N°123/DIR/2026)', max_length=100)),
                ('reference_structure', models.CharField(blank=True, default='', help_text="Référence de la structure externe (ex: N°ABC123 de l'organisme X)", max_length=200)),
                ('service_concerne', models.CharField(blank=True, choices=[('rh', 'Ressources Humaines'), ('comptabilite', 'Comptabilité'), ('direction', 'Direction'), ('technique', 'Service Technique'), ('commercial', 'Commercial'), ('juridique', 'Juridique'), ('informatique', 'Informatique'), ('logistique', 'Logistique'), ('autre', 'Autre')], help_text='Service concerné par ce courrier', max_length=50)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('recu', 'Reçu'), ('en_traitement', 'En traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='recu', help_text='Statut de traitement du courrier', max_length=20)),
                ('fichier', models.FileField(help_text='Fichier scanné du courrier (PDF, image, etc.)', upload_to='courriers/%Y/%m/')),
                ('file_type', models.CharField(default='pdf', help_text='Type de fichier', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='Taille du fichier en octets')),
                ('notes', models.TextField(blank=True, help_text='Notes internes ou observations')),
                ('urgent', models.BooleanField(default=False, help_text='Marquer ce courrier comme urgent/prioritaire')),
                ('version_number', models.IntegerField(default=1, help_text='Numéro de version du courrier')),
                ('est_version_actuelle', models.BooleanField(default=True, help_text="Indique si c'est la version active du courrier")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('contenu_lettre', models.TextField(blank=True, help_text='Contenu HTML de la lettre rédigée sur la plateforme', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Courrier archivé/supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date de suppression', null=True)),
                ('categorie', models.ForeignKey(blank=True, help_text='Catégorie du courrier (devis, demande, facture, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers', to='documents.categorie')),
                ('courrier_parent', models.ForeignKey(blank=True, help_text='Courrier parent pour les versions successives', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.courrier')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a supprimé le courrier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_courriers', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(help_text='Utilisateur ayant enregistré ce courrier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_enregistres', to=settings.AUTH_USER_MODEL)),
                ('reponse_a', models.ForeignKey(blank=True, help_text='Courrier original auquel ce courrier est une réponse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='documents.courrier')),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('courrier_create', 'Création de courrier'), ('courrier_update', 'Modification de courrier'), ('courrier_delete', 'Suppression de courrier'), ('courrier_restore', 'Restauration de courrier'), ('courrier_archive', 'Archivage de courrier'), ('affectation_create', 'Affectation de courrier'), ('affectation_accuse', 'Accusé de réception'), ('affectation_start', 'Début de traitement'), ('affectation_validate', 'Validation'), ('affectation_reject', 'Rejet'), ('affectation_sign', 'Signature'), ('affectation_renvoye', 'Renvoi de courrier'), ('affectation_repondre', 'Réponse au courrier'), ('partage_email', 'Partage par email'), ('partage_whatsapp', 'Partage par WhatsApp'), ('commentaire_add', 'Ajout de commentaire'), ('user_login', 'Connexion'), ('user_logout', 'Déconnexion'), ('user_create', "Création d'utilisateur"), ('user_update', "Modification d'utilisateur"), ('user_delete', "Suppression d'utilisateur"), ('urgent_mark', 'Marquage urgent'), ('urgent_unmark', 'Retrait marquage urgent')], max_length=50)),
                ('description', models.TextField()),
                ('utilisateur_username', models.CharField(max_length=150)),
                ('utilisateur_nom_complet', models.CharField(blank=True, max_length=255)),
                ('courrier_numero', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_log', to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_log', to='documents.courrier')),
            ],
            options={
                'verbose_name': "Log d'action",
                'verbose_name_plural': "Logs d'actions",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourrierPieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(help_text='Fichier joint', upload_to='courriers/pieces_jointes/%Y/%m/')),
                ('nom_fichier', models.CharField(blank=True, help_text='Nom original du fichier', max_length=255)),
                ('file_type', models.CharField(default='pdf', help_text='Type de fichier (pdf, image, etc.)', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='Taille du fichier en octets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(help_text='Courrier auquel appartient cette pièce jointe', on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='documents.courrier')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_jointes_uploadees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_partage', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], help_text='Méthode de partage utilisée', max_length=20)),
                ('destinataire', models.CharField(help_text='Email ou numéro de téléphone du destinataire', max_length=255)),
                ('message', models.TextField(blank=True, help_text="Message d'accompagnement du partage")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure du partage')),
                ('courrier', models.ForeignKey(help_text='Courrier qui a été partagé', on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='documents.courrier')),
                ('partage_par', models.ForeignKey(help_text='Utilisateur ayant effectué le partage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partages_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage de courrier',
                'verbose_name_plural': 'Partages de courriers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['-created_at'], name='documents_c_created_80f1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['numero_registre'], name='documents_c_numero__c51dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['type_courrier', 'statut'], name='documents_c_type_co_9cb10d_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['-timestamp'], name='documents_a_timesta_5065e5_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='documents_a_action__584eca_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['utilisateur', '-timestamp'], name='documents_a_utilisa_205551_idx'),
        ),
        migrations.AddIndex(
            model_name='partagelog',
            index=models.Index(fields=['-created_at'], name='documents_p_created_b38bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='partagelog',
            index=models.Index(fields=['courrier', 'type_partage'], name='documents_p_courrie_ec0874_idx'),
        ),
    ]
