# Generated by Django 5.2.11 on 2026-04-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationcourrier',
            name='circuit',
            field=models.ForeignKey(blank=True, help_text="Circuit d'affectation auquel appartient cette affectation (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='documents.circuitaffectation'),
        ),
        migrations.AddField(
            model_name='affectationcourrier',
            name='etape_numero',
            field=models.PositiveIntegerField(default=1, help_text="Numéro d'étape dans le circuit (mode séquentiel)"),
        ),
        migrations.DeleteModel(
            name='AffectationService',
        ),
    ]
