# Generated by Django 5.2.11 on 2026-04-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_affectationcourrier_circuit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairecourrier',
            name='affectation',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='affectation',
        ),
        migrations.RemoveField(
            model_name='circuitaffectation',
            name='courrier',
        ),
        migrations.RemoveField(
            model_name='circuitaffectation',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='commentairecourrier',
            name='auteur',
        ),
        migrations.AlterUniqueTogether(
            name='fichiercourrierversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fichiercourrierversion',
            name='courrier',
        ),
        migrations.RemoveField(
            model_name='fichiercourrierversion',
            name='cree_par',
        ),
        migrations.DeleteModel(
            name='AffectationCourrier',
        ),
        migrations.DeleteModel(
            name='CircuitAffectation',
        ),
        migrations.DeleteModel(
            name='CommentaireCourrier',
        ),
        migrations.DeleteModel(
            name='FichierCourrierVersion',
        ),
    ]
