# Generated by Django 5.2.11 on 2026-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_visibility_alter_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Taille du fichier en octets'),
        ),
    ]
