# Generated by Django 5.2.11 on 2026-02-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_sharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerequest',
            name='rejection_count',
            field=models.IntegerField(default=0, help_text='Nombre de fois que la demande a été rejetée'),
        ),
    ]
