# Generated by Django 5.2.11 on 2026-02-18 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_sharerequest_rejection_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registre', models.CharField(editable=False, help_text="Numéro d'enregistrement généré automatiquement", max_length=50, unique=True)),
                ('type_courrier', models.CharField(choices=[('entrant', 'Courrier Entrant'), ('sortant', 'Courrier Sortant')], help_text='Type de courrier (entrant ou sortant)', max_length=20)),
                ('date_reception', models.DateField(blank=True, help_text='Date de réception du courrier entrant', null=True)),
                ('date_envoi', models.DateField(blank=True, help_text="Date d'envoi du courrier sortant", null=True)),
                ('expediteur', models.CharField(help_text="Nom ou organisation de l'expéditeur", max_length=255)),
                ('destinataire', models.CharField(help_text='Nom ou organisation du destinataire', max_length=255)),
                ('objet', models.CharField(help_text='Objet ou sujet du courrier', max_length=500)),
                ('reference', models.CharField(blank=True, help_text='Référence du courrier (ex: N°123/DIR/2026)', max_length=100)),
                ('service_concerne', models.CharField(blank=True, choices=[('rh', 'Ressources Humaines'), ('comptabilite', 'Comptabilité'), ('direction', 'Direction'), ('technique', 'Service Technique'), ('commercial', 'Commercial'), ('juridique', 'Juridique'), ('informatique', 'Informatique'), ('logistique', 'Logistique'), ('autre', 'Autre')], help_text='Service concerné par ce courrier', max_length=50)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_traitement', 'En traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='recu', help_text='Statut de traitement du courrier', max_length=20)),
                ('fichier', models.FileField(help_text='Fichier scanné du courrier (PDF, image, etc.)', upload_to='courriers/%Y/%m/')),
                ('file_type', models.CharField(default='pdf', help_text='Type de fichier', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='Taille du fichier en octets')),
                ('notes', models.TextField(blank=True, help_text='Notes internes ou observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('enregistre_par', models.ForeignKey(help_text='Utilisateur ayant enregistré ce courrier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='documents_c_created_80f1a9_idx'), models.Index(fields=['numero_registre'], name='documents_c_numero__c51dfc_idx'), models.Index(fields=['type_courrier', 'statut'], name='documents_c_type_co_9cb10d_idx')],
            },
        ),
    ]
