# Generated by Django 5.2.11 on 2026-02-18 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_courrier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_partage', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], help_text='Méthode de partage utilisée', max_length=20)),
                ('destinataire', models.CharField(help_text='Email ou numéro de téléphone du destinataire', max_length=255)),
                ('message', models.TextField(blank=True, help_text="Message d'accompagnement du partage")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure du partage')),
                ('courrier', models.ForeignKey(help_text='Courrier qui a été partagé', on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='documents.courrier')),
                ('partage_par', models.ForeignKey(help_text='Utilisateur ayant effectué le partage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partages_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage de courrier',
                'verbose_name_plural': 'Partages de courriers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='documents_p_created_b38bcc_idx'), models.Index(fields=['courrier', 'type_partage'], name='documents_p_courrie_ec0874_idx')],
            },
        ),
    ]
