# Generated by Django 5.2.11 on 2026-02-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_partagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='urgent',
            field=models.BooleanField(default=False, help_text='Marquer ce courrier comme urgent/prioritaire'),
        ),
    ]
