# Generated by Django 5.2.11 on 2026-02-20 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_courrier_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='courrier_parent',
            field=models.ForeignKey(blank=True, help_text='Courrier parent pour les versions successives', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.courrier'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='est_version_actuelle',
            field=models.BooleanField(default=True, help_text="Indique si c'est la version active du courrier"),
        ),
        migrations.AddField(
            model_name='courrier',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Numéro de version du courrier'),
        ),
    ]
