# Generated by Django 5.2.11 on 2026-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_add_version_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='destinataire',
            field=models.CharField(blank=True, default='', help_text='Nom ou organisation du destinataire', max_length=255),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='expediteur',
            field=models.CharField(blank=True, default='', help_text="Nom ou organisation de l'expéditeur", max_length=255),
        ),
    ]
