# Generated by Django 5.2.11 on 2026-02-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_courrier_destinataire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='courrier',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text='Catégorie du courrier (devis, demande, facture, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers', to='documents.categorie'),
        ),
    ]
