# Generated by Django 5.2.11 on 2026-03-03 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_categorie_courrier_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationCourrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text="Note de l'affecteur")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('lu', 'Lu'), ('en_traitement', 'En traitement'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('signe', 'Signé')], default='en_attente', max_length=20)),
                ('commentaire_traitement', models.TextField(blank=True, help_text="Commentaire de l'utilisateur lors du traitement")),
                ('motif_rejet', models.TextField(blank=True, help_text='Motif en cas de rejet')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Date de première lecture', null=True)),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date de validation/rejet/signature', null=True)),
                ('affecte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='documents.courrier')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers_affectes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation de courrier',
                'verbose_name_plural': 'Affectations de courriers',
                'ordering': ['-date_affectation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireCourrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='documents.affectationcourrier')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='affectationcourrier',
            index=models.Index(fields=['utilisateur', 'statut'], name='documents_a_utilisa_d11635_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationcourrier',
            index=models.Index(fields=['-date_affectation'], name='documents_a_date_af_0a29e3_idx'),
        ),
    ]
