# Generated by Django 5.2.11 on 2026-03-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_deleted_at_document_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date de suppression', null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a supprimé le courrier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_courriers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrier',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Courrier archivé/supprimé'),
        ),
    ]
