# Generated by Django 5.2.11 on 2026-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_courrier_deleted_at_courrier_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='date_circulation',
            field=models.DateField(blank=True, help_text='Date de circulation du courrier interne', null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='mode_envoi',
            field=models.CharField(blank=True, choices=[('postal', 'Courrier postal'), ('email', 'Email'), ('fax', 'Fax'), ('main_propre', 'Remise en main propre'), ('coursier', 'Coursier'), ('autre', 'Autre')], default='', help_text="Mode d'envoi du courrier sortant", max_length=50),
        ),
        migrations.AddField(
            model_name='courrier',
            name='mode_reception',
            field=models.CharField(blank=True, choices=[('postal', 'Courrier postal'), ('email', 'Email'), ('fax', 'Fax'), ('main_propre', 'Remise en main propre'), ('coursier', 'Coursier'), ('autre', 'Autre')], default='', help_text='Mode de réception du courrier entrant', max_length=50),
        ),
        migrations.AddField(
            model_name='courrier',
            name='service_destinataire',
            field=models.CharField(blank=True, choices=[('rh', 'Ressources Humaines'), ('comptabilite', 'Comptabilité'), ('direction', 'Direction'), ('technique', 'Service Technique'), ('commercial', 'Commercial'), ('juridique', 'Juridique'), ('informatique', 'Informatique'), ('logistique', 'Logistique'), ('autre', 'Autre')], default='', help_text='Service destinataire (courrier interne)', max_length=50),
        ),
        migrations.AddField(
            model_name='courrier',
            name='service_emetteur',
            field=models.CharField(blank=True, choices=[('rh', 'Ressources Humaines'), ('comptabilite', 'Comptabilité'), ('direction', 'Direction'), ('technique', 'Service Technique'), ('commercial', 'Commercial'), ('juridique', 'Juridique'), ('informatique', 'Informatique'), ('logistique', 'Logistique'), ('autre', 'Autre')], default='', help_text='Service émetteur (courrier interne)', max_length=50),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='destinataire',
            field=models.CharField(blank=True, default='', help_text='Nom ou organisation du destinataire (courrier sortant)', max_length=255),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='expediteur',
            field=models.CharField(blank=True, default='', help_text="Nom ou organisation de l'expéditeur (courrier entrant)", max_length=255),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='type_courrier',
            field=models.CharField(choices=[('entrant', 'Courrier Entrant'), ('sortant', 'Courrier Sortant'), ('interne', 'Courrier Interne')], help_text='Type de courrier (entrant ou sortant)', max_length=20),
        ),
    ]
