# Generated by Django 5.2.11 on 2026-03-11 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_courrier_date_circulation_courrier_mode_envoi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierCourrierVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(help_text='Fichier de cette version', upload_to='courriers/versions/%Y/%m/')),
                ('version_number', models.PositiveIntegerField(help_text='Numéro de version (1, 2, 3...)')),
                ('notes_version', models.TextField(blank=True, help_text="Notes décrivant cette version (ex: 'Signé par X', 'Annoté le...')")),
                ('est_version_actuelle', models.BooleanField(default=False, help_text="Indique si c'est la version active affichée")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création de cette version')),
                ('courrier', models.ForeignKey(help_text='Courrier auquel appartient cette version', on_delete=django.db.models.deletion.CASCADE, related_name='fichier_versions', to='documents.courrier')),
                ('cree_par', models.ForeignKey(blank=True, help_text='Utilisateur ayant créé cette version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_courrier_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de fichier courrier',
                'verbose_name_plural': 'Versions de fichiers courrier',
                'ordering': ['-version_number'],
                'unique_together': {('courrier', 'version_number')},
            },
        ),
    ]
